#!/bin/bash
# Mayari DMG Builder Script
# Creates a distributable DMG file for macOS
# Now Python-free! Uses native Swift KokoroTTS

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_DIR/build"
DMG_DIR="$BUILD_DIR/dmg"
RELEASE_DIR="$BUILD_DIR/macos/Build/Products/Release"
APP_NAME="Mayari"
DMG_NAME="Mayari"
VERSION=$(grep 'version:' "$PROJECT_DIR/pubspec.yaml" | head -1 | cut -d'+' -f1 | cut -d':' -f2 | xargs)
APP_FILENAME_FILE="$PROJECT_DIR/macos/Flutter/ephemeral/.app_filename"

echo "========================================"
echo "Mayari DMG Builder (Native Swift TTS)"
echo "Version: $VERSION"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}[OK]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check for macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    print_error "This script is only for macOS"
    exit 1
fi

# Check macOS version (need 15.0+ for KokoroSwift)
MACOS_VERSION=$(sw_vers -productVersion | cut -d. -f1)
if [ "$MACOS_VERSION" -lt 15 ]; then
    print_warning "macOS 15.0+ recommended for native TTS. Current: $(sw_vers -productVersion)"
fi

# Check for create-dmg (optional but recommended)
HAS_CREATE_DMG=false
if command -v create-dmg &> /dev/null; then
    HAS_CREATE_DMG=true
    print_status "create-dmg found"
else
    print_warning "create-dmg not found. Using basic DMG creation."
    print_warning "For prettier DMGs, install: brew install create-dmg"
fi

echo ""
echo "Step 1: Building Release App..."
echo "--------------------------------"

cd "$PROJECT_DIR"

# Clean previous build
echo "Cleaning previous build..."
flutter clean > /dev/null 2>&1
flutter pub get > /dev/null

# Build release
echo "Building release app (this may take a few minutes)..."
flutter build macos --release

# Resolve the real app product name generated by Flutter/Xcode (for example mayari_temp.app)
if [ -f "$APP_FILENAME_FILE" ]; then
    BUILT_APP_FILE="$(cat "$APP_FILENAME_FILE" | tr -d '[:space:]')"
else
    BUILT_APP_FILE=""
fi

if [ -n "$BUILT_APP_FILE" ] && [ -d "$RELEASE_DIR/$BUILT_APP_FILE" ]; then
    SOURCE_APP_PATH="$RELEASE_DIR/$BUILT_APP_FILE"
elif [ -d "$RELEASE_DIR/mayari_temp.app" ]; then
    SOURCE_APP_PATH="$RELEASE_DIR/mayari_temp.app"
elif [ -d "$RELEASE_DIR/$APP_NAME.app" ]; then
    SOURCE_APP_PATH="$RELEASE_DIR/$APP_NAME.app"
else
    print_error "Built app not found in $RELEASE_DIR"
    exit 1
fi

# Always recreate Mayari.app from the just-built source app to avoid stale/broken bundles.
rm -rf "$RELEASE_DIR/$APP_NAME.app"
ditto "$SOURCE_APP_PATH" "$RELEASE_DIR/$APP_NAME.app"

print_status "Release app built"

# Copy Swift Package Manager frameworks to app bundle
# These are built separately and need to be embedded manually
PACKAGE_FRAMEWORKS_DIR="$RELEASE_DIR/PackageFrameworks"
APP_FRAMEWORKS_DIR="$RELEASE_DIR/$APP_NAME.app/Contents/Frameworks"
if [ -d "$PACKAGE_FRAMEWORKS_DIR" ]; then
    echo "Copying Swift Package frameworks..."
    mkdir -p "$APP_FRAMEWORKS_DIR"
    for framework in "$PACKAGE_FRAMEWORKS_DIR"/*.framework; do
        if [ -d "$framework" ]; then
            framework_name=$(basename "$framework")
            # Only copy if not already present
            if [ ! -d "$APP_FRAMEWORKS_DIR/$framework_name" ]; then
                cp -R "$framework" "$APP_FRAMEWORKS_DIR/"
                echo "  Copied: $framework_name"
            fi
        fi
    done
    print_status "Swift Package frameworks embedded"
fi

echo ""
echo "Step 2: Preparing DMG Contents..."
echo "----------------------------------"

# Clean and create DMG directory
rm -rf "$DMG_DIR"
mkdir -p "$DMG_DIR"

# Copy app
cp -R "$RELEASE_DIR/$APP_NAME.app" "$DMG_DIR/"
print_status "App copied to DMG staging"

# Embed license files in the app bundle
RESOURCES_DIR="$DMG_DIR/$APP_NAME.app/Contents/Resources"
if [ -f "$PROJECT_DIR/LICENSE" ]; then
    cp "$PROJECT_DIR/LICENSE" "$RESOURCES_DIR/LICENSE"
fi
if [ -f "$PROJECT_DIR/BINARY-LICENSE.txt" ]; then
    cp "$PROJECT_DIR/BINARY-LICENSE.txt" "$RESOURCES_DIR/BINARY-LICENSE.txt"
fi

# Bundle default PDF files in the app
PDF_SRC_DIR="$PROJECT_DIR/pdf"
if [ -d "$PDF_SRC_DIR" ]; then
    PDF_DEST_DIR="$RESOURCES_DIR/pdf"
    mkdir -p "$PDF_DEST_DIR"
    cp -R "$PDF_SRC_DIR"/*.pdf "$PDF_DEST_DIR/" 2>/dev/null || true
    print_status "Bundled PDF files in app"
fi

# Copy license files to DMG root
if [ -f "$PROJECT_DIR/LICENSE" ]; then
    cp "$PROJECT_DIR/LICENSE" "$DMG_DIR/LICENSE"
fi
if [ -f "$PROJECT_DIR/BINARY-LICENSE.txt" ]; then
    cp "$PROJECT_DIR/BINARY-LICENSE.txt" "$DMG_DIR/BINARY-LICENSE.txt"
fi

# No Python backend needed - using native Swift TTS!
print_status "Native Swift TTS - no Python backend required"

# Create README for DMG
cat > "$DMG_DIR/README.txt" << 'EOF'
Mayari PDF Reader with Native Kokoro TTS
========================================

Installation:
1. Drag "Mayari.app" to your Applications folder
2. Launch "Mayari.app" from Applications

Requirements:
- macOS 15.0 (Sequoia) or later
- Apple Silicon (M1/M2/M3/M4) recommended

Note: The Kokoro TTS model (~350MB) will download automatically
on first use. This requires an internet connection.

For more information, visit the project repository.
EOF

print_status "README created"

# Create Applications symlink
ln -sf /Applications "$DMG_DIR/Applications"
print_status "Applications symlink created"

echo ""
echo "Step 3: Creating DMG..."
echo "------------------------"

DMG_OUTPUT="$BUILD_DIR/${DMG_NAME}-${VERSION}.dmg"
rm -f "$DMG_OUTPUT"

if [ "$HAS_CREATE_DMG" = true ]; then
    # Use create-dmg for a nice DMG
    create-dmg \
        --volname "$APP_NAME $VERSION" \
        --volicon "$PROJECT_DIR/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png" \
        --window-pos 200 120 \
        --window-size 600 400 \
        --icon-size 100 \
        --icon "$APP_NAME.app" 150 190 \
        --icon "Applications" 450 190 \
        --icon "README.txt" 300 300 \
        --hide-extension "$APP_NAME.app" \
        --app-drop-link 450 190 \
        "$DMG_OUTPUT" \
        "$DMG_DIR" \
        2>/dev/null || {
            print_warning "create-dmg failed, falling back to basic DMG"
            HAS_CREATE_DMG=false
        }
fi

if [ "$HAS_CREATE_DMG" = false ]; then
    # Basic DMG creation
    hdiutil create -volname "$APP_NAME $VERSION" \
        -srcfolder "$DMG_DIR" \
        -ov -format UDZO \
        "$DMG_OUTPUT"
fi

print_status "DMG created: $DMG_OUTPUT"

echo ""
echo "Step 4: Generating Checksums..."
echo "--------------------------------"

# Create dist directory for release artifacts
DIST_DIR="$PROJECT_DIR/dist"
mkdir -p "$DIST_DIR"

# Move DMG to dist directory
DMG_FINAL="$DIST_DIR/${DMG_NAME}-${VERSION}.dmg"
mv "$DMG_OUTPUT" "$DMG_FINAL"

# Generate SHA256 checksum
cd "$DIST_DIR"
shasum -a 256 "$(basename "$DMG_FINAL")" > "$(basename "$DMG_FINAL").sha256"
SHA256=$(awk '{print $1}' "$(basename "$DMG_FINAL").sha256")
print_status "SHA256 checksum generated"

# Copy release notes if present
RELEASE_NOTES_SRC="$PROJECT_DIR/RELEASE_NOTES.md"
RELEASE_NOTES_NAME="${DMG_NAME}-${VERSION}-RELEASE_NOTES.md"
if [ -f "$RELEASE_NOTES_SRC" ]; then
    cp "$RELEASE_NOTES_SRC" "$DIST_DIR/$RELEASE_NOTES_NAME"
    shasum -a 256 "$RELEASE_NOTES_NAME" > "$RELEASE_NOTES_NAME.sha256"
    print_status "Release notes copied"
fi

echo ""
echo "Step 5: Summary..."
echo "-------------------"

print_status "DMG staging kept at: $DMG_DIR"

echo ""
echo "========================================"
echo "Build Complete! (Python-Free)"
echo "========================================"
echo ""
echo "DMG file: $DMG_FINAL"
echo "Size: $(du -h "$DMG_FINAL" | cut -f1)"
echo "SHA256: $SHA256"
echo ""
echo "Release artifacts in: $DIST_DIR"
ls -la "$DIST_DIR"
echo ""
echo "To test the DMG:"
echo "  open $DMG_FINAL"
echo ""
